export const COMMON_ERROR_CODE = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export const AUTH_ERROR_CODE = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_MISSING: 'REFRESH_TOKEN_MISSING',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_REQUEST_ORIGIN: 'INVALID_REQUEST_ORIGIN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
} as const;

export const USER_ERROR_CODE = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export const GITHUB_ERROR_CODE = {
  NOT_CONNECTED_GITHUB_YET: 'NOT_CONNECTED_GITHUB_YET',
  CANNOT_GET_LIST_REPOS_FROM_GITHUB: 'CANNOT_GET_LIST_REPOS_FROM_GITHUB',
} as const;

export const PROJECT_ERROR_CODE = {
  NOT_ACCESS_TO_PROJECT: 'NOT_ACCESS_TO_PROJECT',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  HOST_PORT_ALREADY_EXISTS: 'HOST_PORT_ALREADY_EXISTS',
  GITHUB_REPO_ALREADY_EXISTS: 'GITHUB_REPO_ALREADY_EXISTS',
  PROJECT_SLUG_ALREADY_EXISTS: 'PROJECT_SLUG_ALREADY_EXISTS',
  CONTAINER_NAME_ALREADY_EXISTS: 'CONTAINER_NAME_ALREADY_EXISTS',
} as const;

export const DEPLOYMENT_ERROR_CODE = {
  PROJECT_NOT_DEPLOYABLE: 'PROJECT_NOT_DEPLOYABLE',
  PROJECT_NOT_ACTIVE: 'PROJECT_NOT_ACTIVE',
  PROJECT_RUNNER_NOT_SUPPORTED: 'PROJECT_RUNNER_NOT_SUPPORTED',
  PROJECT_DEPLOY_CONFIG_MISSING: 'PROJECT_DEPLOY_CONFIG_MISSING',
  ACTIVE_DEPLOYMENT_EXISTS: 'ACTIVE_DEPLOYMENT_EXISTS',
} as const;

export type CommonErrorCode =
  (typeof COMMON_ERROR_CODE)[keyof typeof COMMON_ERROR_CODE];
export type AuthErrorCode =
  (typeof AUTH_ERROR_CODE)[keyof typeof AUTH_ERROR_CODE];
export type UserErrorCode =
  (typeof USER_ERROR_CODE)[keyof typeof USER_ERROR_CODE];
export type GithubErrorCode =
  (typeof GITHUB_ERROR_CODE)[keyof typeof GITHUB_ERROR_CODE];
export type ProjectErrorCode =
  (typeof PROJECT_ERROR_CODE)[keyof typeof PROJECT_ERROR_CODE];
export type DeploymentErrorCode =
  (typeof DEPLOYMENT_ERROR_CODE)[keyof typeof DEPLOYMENT_ERROR_CODE];

export type ErrorCode =
  | CommonErrorCode
  | AuthErrorCode
  | UserErrorCode
  | GithubErrorCode
  | ProjectErrorCode
  | DeploymentErrorCode;
